Add defgate as sequence to quil language spec
quil-lang/quil pull request #53
Opened 2022-02-22 22:41 UTC by Spin1Half

2022-02-22 22:44 UTC, Spin1Half commented
P.S. These changes include a few typo fixes unrelated to sequence gate definitions

2022-02-23 20:02 UTC, Spin1Half commented
I've just noticed that nothing is preventing multiple sequence gate definitions with the same name from happening. But this seems to also be the case for other def gates as well (I tested with pauli sum and it seemed to compile, though I didnt nail down the behavior, e.g. which gate it will actually use if they are different unitaries).

Not sure if its worth having some sort of validation to prevent this (until something like defgate alternatives is implemented)

2022-03-02 02:08 UTC, kilimanjaro reviewed
Overall this is looking pretty good. Just a few minor things.

2022-03-03 22:04 UTC, Spin1Half commented on specgen/spec/sec-gates.s
> +                @ms{Expression List}
If it adds anything to this discussion, I tried getting quilc to compile something like `H() 01` and it didn't like it.

2022-03-03 22:11 UTC, Spin1Half commented on specgen/spec/sec-circuits.s
> +@ms{Indent}@rep[:min 0]{@ms{Circuit Instruction}}
Right, I think my issue was that a <Circuit Instruction> contains both <Indent> and <Terminator> which seems to suggest that 2 newlines are necessary since <Indent> := <Newline><..>

2022-03-15 02:59 UTC, kilimanjaro commented
lgtm, although I do not have write access

2022-03-18 00:00 UTC, stylewarning requested changes

2022-03-18 20:20 UTC, stylewarning commented on specgen/spec/sec-gates.s
> +                @ms{Expression List}
H() 0 is invalid.

2022-03-18 20:20 UTC, stylewarning approved these changes

2022-03-18 20:21 UTC, merged